baseURL = "http://wbean1.info/"
languageCode = "en-us"
title = "about wbean1"
theme = "nix"
publishDir = "docs"

[params]
  GithubID = "wbean1"
  TwitterID = "bbeanis"
  FacebookID = "100000921827528"
  LinkedInID = "william-bean-a0133a101"
  Name = "William Bean"
  HeaderUsername = "root"
  HeaderHostname = "wbean1.info"
  Email = "wbean1@gmail.com"
  About = "I'm a technology guy working for John Deere in Illinois.  We make some cool big equipment.  I've done app hosting of various sorts on linux for several years, and have found myself operating platforms in various clouds.  Check out my resume & blog!" 
  ProfilePicture = "/pic.jpg"
  CvURL = "/resume.pdf"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/posts"
  [[menu.header]]
    name = "resume"
    weight = 1
    url = "/resume"
